// <auto-generated />
using System;
using System.Collections.Generic;
using CoreBancario.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreBancario.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(CoreBancarioDbContext))]
    [Migration("20260726212502_AdicionaIndiceContraparte")]
    partial class AdicionaIndiceContraparte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreBancario.Dominio.Ledger.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<Guid>("ContraparteId")
                        .HasColumnType("uuid")
                        .HasColumnName("contraparte_id");

                    b.Property<string>("ContraparteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contraparte_nome");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("LiquidacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("liquidacao_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Valor", "CoreBancario.Dominio.Ledger.Lancamento.Valor#Dinheiro", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moeda");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(19,2)")
                                .HasColumnName("valor");
                        });

                    b.HasKey("Id")
                        .HasName("pk_lancamentos");

                    b.ToTable("lancamentos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
